
sed -i 's|$auto$clkbufmap.cc:294:execute$1061|clk0|' $(find . -type f -name "fabric_up5bit_counter_dual_clock_top_formal_verification.v")
sed -i 's|$auto$clkbufmap.cc:294:execute$1058|clk1|' $(find . -type f -name "fabric_up5bit_counter_dual_clock_top_formal_verification.v")
sed -i "s|clk_fm\[0\] = clock0\[0\]|clk_fm\[0\] = 1'b0|" $(find . -type f -name "fabric_up5bit_counter_dual_clock_top_formal_verification.v")
# sed -i "s|clk_fm\[14\] = 1'b0|clk_fm\[14\] = clk1|" $(find . -type f -name "fabric_up5bit_counter_dual_clock_top_formal_verification.v")
sed -i "s|clk_fm\[15\] = 1'b0|clk_fm\[15\] = clk0|" $(find . -type f -name "fabric_up5bit_counter_dual_clock_top_formal_verification.v")
# sed -i "s|clk_fm\[1\] = 1'b0|clk_fm\[1\] = clk0|" $(find . -type f -name "fabric_up5bit_counter_dual_clock_top_formal_verification.v")
# sed -i "s|clk_fm\[2\] = 1'b0|clk_fm\[2\] = clk1|" $(find . -type f -name "fabric_up5bit_counter_dual_clock_top_formal_verification.v")
# sed -i "s|clk_fm\[3\] = 1'b0|clk_fm\[3\] = clk1|" $(find . -type f -name "fabric_up5bit_counter_dual_clock_top_formal_verification.v")
# sed -i "s|clk_fm\[4\] = 1'b0|clk_fm\[4\] = clk1|" $(find . -type f -name "fabric_up5bit_counter_dual_clock_top_formal_verification.v")
# sed -i "s|clk_fm\[5\] = 1'b0|clk_fm\[5\] = clk1|" $(find . -type f -name "fabric_up5bit_counter_dual_clock_top_formal_verification.v")
# sed -i "s|clk_fm\[6\] = 1'b0|clk_fm\[6\] = clk1|" $(find . -type f -name "fabric_up5bit_counter_dual_clock_top_formal_verification.v")
# sed -i "s|clk_fm\[7\] = 1'b0|clk_fm\[7\] = clk1|" $(find . -type f -name "fabric_up5bit_counter_dual_clock_top_formal_verification.v")
# sed -i "s|clk_fm\[8\] = 1'b0|clk_fm\[8\] = clk1|" $(find . -type f -name "fabric_up5bit_counter_dual_clock_top_formal_verification.v")
# sed -i "s|clk_fm\[9\] = 1'b0|clk_fm\[9\] = clk1|" $(find . -type f -name "fabric_up5bit_counter_dual_clock_top_formal_verification.v")
# sed -i "s|clk_fm\[10\] = 1'b0|clk_fm\[10\] = clk1|" $(find . -type f -name "fabric_up5bit_counter_dual_clock_top_formal_verification.v")
# sed -i "s|clk_fm\[11\] = 1'b0|clk_fm\[11\] = clk1|" $(find . -type f -name "fabric_up5bit_counter_dual_clock_top_formal_verification.v")
# sed -i "s|clk_fm\[12\] = 1'b0|clk_fm\[12\] = clk1|" $(find . -type f -name "fabric_up5bit_counter_dual_clock_top_formal_verification.v")
# sed -i "s|clk_fm\[13\] = 1'b0|clk_fm\[13\] = clk1|" $(find . -type f -name "fabric_up5bit_counter_dual_clock_top_formal_verification.v")
sed -i "s|global_resetn_fm\[0\] = 1'b0|global_resetn_fm\[0\] = 1'b1|g" $(find . -type f -name "fabric_up5bit_counter_dual_clock_top_formal_verification.v")
