create_clock -period 2.5 design_clk_0
create_clock -period 2.5 design_clk_1
create_clock -period 2.5 design_clk_2
create_clock -period 2.5 design_clk_3
create_clock -period 2.5 design_clk_4
create_clock -period 2.5 design_clk_5
create_clock -period 2.5 design_clk_6
create_clock -period 2.5 design_clk_7
create_clock -period 2.5 design_clk_8
create_clock -period 2.5 design_clk_9
create_clock -period 2.5 design_clk_10
create_clock -period 2.5 design_clk_11
create_clock -period 2.5 design_clk_12
create_clock -period 2.5 design_clk_13
create_clock -period 2.5 design_clk_14
create_clock -period 2.5 design_clk_15