-sv2009 /nfs_eda_sw/softwares/Raptor/instl_dir/04_02_2023_09_15_01/share/raptor/sim_models/rapidsilicon/genesis3/cell_sim_blackbox.v
-set-warning VERI-1063
-vlog-incdir ../../rtl ../ /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/bitstream_simulation_new/test/ArchBench/Testcases/filt_ppi/filt_ppi_golden/../rtl 
-vlog-libdir ../../rtl 
-vlog-libext .v
-vlog-libext .sv
-vlog-define 
-vlog2k /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/bitstream_simulation_new/test/ArchBench/Testcases/filt_ppi/filt_ppi_golden/../rtl/filt_ppi.v
-top filt_ppi
