
sed -i "s|\$auto\$clkbufmap.cc:294:execute\$1411|clock0|g" $(find . -type f -name "fabric_shift_register_formal_random_top_tb.v")
sed -i "s|\$auto\$clkbufmap.cc:294:execute\$1411|clock0|g" $(find . -type f -name "fabric_shift_register_top_formal_verification.v")
sed -i "s|clk_fm\[15\] = 1'b0|clk_fm[15] = clock0|g" $(find . -type f -name "fabric_shift_register_top_formal_verification.v")
sed -i "s|clk_fm\[14\] = 1'b0|clk_fm[14] = clock0|g" $(find . -type f -name "fabric_shift_register_top_formal_verification.v")
sed -i "s|clk_fm\[13\] = 1'b0|clk_fm[13] = clock0|g" $(find . -type f -name "fabric_shift_register_top_formal_verification.v")
sed -i "s|clk_fm\[12\] = 1'b0|clk_fm[12] = clock0|g" $(find . -type f -name "fabric_shift_register_top_formal_verification.v")
sed -i "s|clk_fm\[11\] = 1'b0|clk_fm[11] = clock0|g" $(find . -type f -name "fabric_shift_register_top_formal_verification.v")
sed -i "s|clk_fm\[10\] = 1'b0|clk_fm[10] = clock0|g" $(find . -type f -name "fabric_shift_register_top_formal_verification.v")
sed -i "s|clk_fm\[9\] = 1'b0|clk_fm[9] = clock0|g" $(find . -type f -name "fabric_shift_register_top_formal_verification.v")
sed -i "s|clk_fm\[8\] = 1'b0|clk_fm[8] = clock0|g" $(find . -type f -name "fabric_shift_register_top_formal_verification.v")
sed -i "s|clk_fm\[7\] = 1'b0|clk_fm[7] = clock0|g" $(find . -type f -name "fabric_shift_register_top_formal_verification.v")
sed -i "s|clk_fm\[6\] = 1'b0|clk_fm[6] = clock0|g" $(find . -type f -name "fabric_shift_register_top_formal_verification.v")
sed -i "s|clk_fm\[5\] = 1'b0|clk_fm[5] = clock0|g" $(find . -type f -name "fabric_shift_register_top_formal_verification.v")
sed -i "s|clk_fm\[4\] = 1'b0|clk_fm[4] = clock0|g" $(find . -type f -name "fabric_shift_register_top_formal_verification.v")
sed -i "s|clk_fm\[3\] = 1'b0|clk_fm[3] = clock0|g" $(find . -type f -name "fabric_shift_register_top_formal_verification.v")
sed -i "s|clk_fm\[2\] = 1'b0|clk_fm[2] = clock0|g" $(find . -type f -name "fabric_shift_register_top_formal_verification.v")
sed -i "s|clk_fm\[1\] = 1'b0|clk_fm[1] = clock0|g" $(find . -type f -name "fabric_shift_register_top_formal_verification.v")
sed -i "s|clk_fm\[0\] = 1'b0|clk_fm[0] = clock0|g" $(find . -type f -name "fabric_shift_register_top_formal_verification.v")
sed -i "s|global_resetn_fm\[0\] = 1'b0|global_resetn_fm\[0\] = 1'b1|g" $(find . -type f -name "fabric_shift_register_top_formal_verification.v")