//-------------------------------------------
//	FPGA Synthesizable Verilog Netlist
//	Description: Fabric Netlist Summary
//	Author: Xifan TANG
//	Organization: University of Utah
//-------------------------------------------
//----- Time scale -----
`timescale 1ns / 1ps

// ------ Include defines: preproc flags -----
`include "../../../../fabric10x8/defines.v"
`include "../../../../fabric10x8/fpga_defines.v"

`include "../../../../fabric10x8/SRC/tcbn16ffcllbwp7d5t16p96cpd.v"
`include "../../../../fabric10x8/SRC/tcbn16ffcllbwp7d5t16p96cpdlvt.v"

`include "../../../../fabric10x8/CustomModules/bram/rtl/ql_clkmux.v"
`include "../../../../fabric10x8/CustomModules/bram/rtl/dti_dp_tm16ffcll_1024x18_t8bw2x_m_hc.v"
`include "../../../../fabric10x8/CustomModules/bram/rtl/TDP18K_FIFO.sv"
`include "../../../../fabric10x8/CustomModules/bram/rtl/ufifo_ctl.sv"
`include "../../../../fabric10x8/CustomModules/bram/rtl/TDP36K.sv"
`include "../../../../fabric10x8/CustomModules/bram/rtl/TDP36K_top.sv"

`include "../../../../fabric10x8/CustomModules/dsp/rtl/bw_multiplier.sv"
`include "../../../../fabric10x8/CustomModules/dsp/rtl/dsp.sv"
`include "../../../../fabric10x8/CustomModules/dsp/rtl/dsp_type1_bw.sv"

`include "../../../../fabric10x8/CustomModules/rs_mmff.v"

// ------ Include user-defined netlists -----
`include "../../../../fabric10x8/CustomModules/clock_inverter.v"
`include "../../../../fabric10x8/CustomModules/inverter.v"
`include "../../../../fabric10x8/CustomModules/logic0.v"
`include "../../../../fabric10x8/CustomModules/logic1.v"
// `include "./fabric10x8/sc_verilog/tcbn16ffcllbwp7d5t16p96cpd.v"
`include "../../../../fabric10x8/CustomModules/rs_ioff.v"
`include "../../../../fabric10x8/CustomModules/rs_ff.v"
`include "../../../../fabric10x8/CustomModules/rs_xor_mux2.v"
`include "../../../../fabric10x8/CustomModules/rs_ccff.v"
`include "../../../../fabric10x8/CustomModules/rs_preio.v"
`include "../../../../fabric10x8/CustomModules/RS_DSP.v"
`include "../../../../fabric10x8/CustomModules/RS_BRAM.v"
// ------ Include primitive module netlists -----
`include "../../../../fabric10x8/sub_module/inv_buf_passgate.v"
`include "../../../../fabric10x8/sub_module/arch_encoder.v"
`include "../../../../fabric10x8/sub_module/local_encoder.v"
`include "../../../../fabric10x8/sub_module/mux_primitives.v"
`include "../../../../fabric10x8/sub_module/muxes.v"
`include "../../../../fabric10x8/sub_module/luts.v"
`include "../../../../fabric10x8/sub_module/wires.v"
`include "../../../../fabric10x8/sub_module/memories.v"
`include "../../../../fabric10x8/sub_module/shift_register_banks.v"

// ------ Include logic block netlists -----
`include "../../../../fabric10x8/lb/logical_tile_io_mode_physical__iopad_mode_default__ff.v"
`include "../../../../fabric10x8/lb/logical_tile_io_mode_physical__iopad_mode_default__pad.v"
`include "../../../../fabric10x8/lb/logical_tile_io_mode_physical__iopad.v"
`include "../../../../fabric10x8/lb/logical_tile_io_mode_io_.v"
`include "../../../../fabric10x8/lb/logical_tile_io_corner_mode_physical__iopad_mode_default__ff.v"
`include "../../../../fabric10x8/lb/logical_tile_io_corner_mode_physical__iopad_mode_default__pad.v"
`include "../../../../fabric10x8/lb/logical_tile_io_corner_mode_physical__iopad.v"
`include "../../../../fabric10x8/lb/logical_tile_io_corner_mode_io_corner_.v"
`include "../../../../fabric10x8/lb/logical_tile_clb_mode_default__fle_wrapper_mode_default__comb_block_mode_default__lut_block_mode_default__frac_lut_mode_default__mux_wrap_mode_physical__frac_lut6.v"
`include "../../../../fabric10x8/lb/logical_tile_clb_mode_default__fle_wrapper_mode_default__comb_block_mode_default__lut_block_mode_default__frac_lut_mode_default__mux_wrap.v"
`include "../../../../fabric10x8/lb/logical_tile_clb_mode_default__fle_wrapper_mode_default__comb_block_mode_default__lut_block_mode_default__frac_lut.v"
`include "../../../../fabric10x8/lb/logical_tile_clb_mode_default__fle_wrapper_mode_default__comb_block_mode_default__lut_block.v"
`include "../../../../fabric10x8/lb/logical_tile_clb_mode_default__fle_wrapper_mode_default__comb_block_mode_default__fa_2bit_block_mode_physical__fa_2bit_phy_mode_default__fa_1bit.v"
`include "../../../../fabric10x8/lb/logical_tile_clb_mode_default__fle_wrapper_mode_default__comb_block_mode_default__fa_2bit_block_mode_physical__fa_2bit_phy.v"
`include "../../../../fabric10x8/lb/logical_tile_clb_mode_default__fle_wrapper_mode_default__comb_block_mode_default__fa_2bit_block.v"
`include "../../../../fabric10x8/lb/logical_tile_clb_mode_default__fle_wrapper_mode_default__comb_block.v"
`include "../../../../fabric10x8/lb/logical_tile_clb_mode_default__fle_wrapper_mode_default__ff_wrap_mode_default__ff_half_mode_physical__flop_quad_mode_default__MMFF.v"
`include "../../../../fabric10x8/lb/logical_tile_clb_mode_default__fle_wrapper_mode_default__ff_wrap_mode_default__ff_half_mode_physical__flop_quad.v"
`include "../../../../fabric10x8/lb/logical_tile_clb_mode_default__fle_wrapper_mode_default__ff_wrap_mode_default__ff_half.v"
`include "../../../../fabric10x8/lb/logical_tile_clb_mode_default__fle_wrapper_mode_default__ff_wrap.v"
`include "../../../../fabric10x8/lb/logical_tile_clb_mode_default__fle_wrapper.v"
`include "../../../../fabric10x8/lb/logical_tile_clb_mode_clb_.v"
`include "../../../../fabric10x8/lb/logical_tile_dsp_mode_default__dsp_rtl_mode_physical__dsp_phy.v"
`include "../../../../fabric10x8/lb/logical_tile_dsp_mode_default__dsp_rtl.v"
`include "../../../../fabric10x8/lb/logical_tile_dsp_mode_default__opt_mode_default__logic0.v"
`include "../../../../fabric10x8/lb/logical_tile_dsp_mode_default__opt_mode_default__logic1.v"
`include "../../../../fabric10x8/lb/logical_tile_dsp_mode_default__opt.v"
`include "../../../../fabric10x8/lb/logical_tile_dsp_mode_default__sr_opt_mode_default__sr_inv.v"
`include "../../../../fabric10x8/lb/logical_tile_dsp_mode_default__sr_opt.v"
`include "../../../../fabric10x8/lb/logical_tile_dsp_mode_default__clk_opt_mode_default__clk_inv.v"
`include "../../../../fabric10x8/lb/logical_tile_dsp_mode_default__clk_opt.v"
`include "../../../../fabric10x8/lb/logical_tile_dsp_mode_default__z_pad.v"
`include "../../../../fabric10x8/lb/logical_tile_dsp_mode_dsp_.v"
`include "../../../../fabric10x8/lb/logical_tile_bram_mode_default__bram_rtl_mode_physical__bram_phy.v"
`include "../../../../fabric10x8/lb/logical_tile_bram_mode_default__bram_rtl.v"
`include "../../../../fabric10x8/lb/logical_tile_bram_mode_default__sr_opt_mode_default__sr_inv.v"
`include "../../../../fabric10x8/lb/logical_tile_bram_mode_default__sr_opt.v"
`include "../../../../fabric10x8/lb/logical_tile_bram_mode_default__flush_opt_mode_default__logic0.v"
`include "../../../../fabric10x8/lb/logical_tile_bram_mode_default__flush_opt_mode_default__logic1.v"
`include "../../../../fabric10x8/lb/logical_tile_bram_mode_default__flush_opt.v"
`include "../../../../fabric10x8/lb/logical_tile_bram_mode_default__clk_opt_mode_default__clk_inv.v"
`include "../../../../fabric10x8/lb/logical_tile_bram_mode_default__clk_opt.v"
`include "../../../../fabric10x8/lb/logical_tile_bram_mode_default__ff_wrap_mode_default__ff_group_mode_physical__flop_group_mode_default__MMFF.v"
`include "../../../../fabric10x8/lb/logical_tile_bram_mode_default__ff_wrap_mode_default__ff_group_mode_physical__flop_group.v"
`include "../../../../fabric10x8/lb/logical_tile_bram_mode_default__ff_wrap_mode_default__ff_group.v"
`include "../../../../fabric10x8/lb/logical_tile_bram_mode_default__ff_wrap.v"
`include "../../../../fabric10x8/lb/logical_tile_bram_mode_bram_.v"
`include "../../../../fabric10x8/lb/grid_io_top.v"
`include "../../../../fabric10x8/lb/grid_io_right.v"
`include "../../../../fabric10x8/lb/grid_io_bottom.v"
`include "../../../../fabric10x8/lb/grid_io_left.v"
`include "../../../../fabric10x8/lb/grid_io_right_top.v"
`include "../../../../fabric10x8/lb/grid_io_right_bottom.v"
`include "../../../../fabric10x8/lb/grid_clb.v"
`include "../../../../fabric10x8/lb/grid_dsp.v"
`include "../../../../fabric10x8/lb/grid_bram.v"

// ------ Include routing module netlists -----
`include "../../../../fabric10x8/routing/sb_0__0_.v"
`include "../../../../fabric10x8/routing/sb_0__1_.v"
`include "../../../../fabric10x8/routing/sb_0__8_.v"
`include "../../../../fabric10x8/routing/sb_1__0_.v"
`include "../../../../fabric10x8/routing/sb_1__1_.v"
`include "../../../../fabric10x8/routing/sb_1__2_.v"
`include "../../../../fabric10x8/routing/sb_1__8_.v"
`include "../../../../fabric10x8/routing/sb_2__0_.v"
`include "../../../../fabric10x8/routing/sb_2__1_.v"
`include "../../../../fabric10x8/routing/sb_2__8_.v"
`include "../../../../fabric10x8/routing/sb_10__0_.v"
`include "../../../../fabric10x8/routing/sb_10__1_.v"
`include "../../../../fabric10x8/routing/sb_10__2_.v"
`include "../../../../fabric10x8/routing/sb_10__8_.v"
`include "../../../../fabric10x8/routing/cbx_1__0_.v"
`include "../../../../fabric10x8/routing/cbx_1__1_.v"
`include "../../../../fabric10x8/routing/cbx_2__2_.v"
`include "../../../../fabric10x8/routing/cbx_10__1_.v"
`include "../../../../fabric10x8/routing/cby_0__1_.v"
`include "../../../../fabric10x8/routing/cby_1__1_.v"
`include "../../../../fabric10x8/routing/cby_2__2_.v"

// ------ Include fabric top-level netlists -----
`include "../../../../fabric10x8/fpga_top.v"

