sed -i "s|// ----- Begin reset signal generation -----|assign counter_in = out_gfpga;|g" $(find . -type f -name "fabric_ring_counter_formal_random_top_tb.v")
sed -i "s|// reg \[0:0\] counter_in\[98\];|reg \[99:0\] data;|g" $(find . -type f -name "fabric_ring_counter_formal_random_top_tb.v")
sed -i "s|// reg \[0:0\] counter_in\[97\];|reg \[31:0\] error=0;|g" $(find . -type f -name "fabric_ring_counter_formal_random_top_tb.v")
sed -i "s|//----- Default net type -----|\`define REGISTER_WIDTH 100|g" $(find . -type f -name "fabric_ring_counter_formal_random_top_tb.v")
sed -i "s|clk_fm\[15\] = 1'b0;|clk_fm\[15\] = clock0;|g" $(find . -type f -name "fabric_ring_counter_top_formal_verification.v")
sed -i "s|global_resetn_fm\[0\] = 1'b0;|global_resetn_fm\[0\] = 1'b1;|g" $(find . -type f -name "fabric_ring_counter_top_formal_verification.v")
sed -i "s|dumpvars(1|dumpvars(0|g" $(find . -type f -name "fabric_ring_counter_formal_random_top_tb.v")
