sed -i "s|// reg \[0:0\] A\[0\];|bit \[0:37\] Y_pred=0;|g" $(find . -type f -name "fabric_eight_mult_20x18_unsigned_regout_formal_random_top_tb.v")
sed -i "s|// reg \[0:0\] A\[1\];|bit \[31:0\] error;|g" $(find . -type f -name "fabric_eight_mult_20x18_unsigned_regout_formal_random_top_tb.v")
sed -i "s|//	FPGA Synthesizable Verilog Netlist|\`define EIGHT_MULT_20x18_UNSIGNED_REGOUT 2|g" $(find . -type f -name "fabric_eight_mult_20x18_unsigned_regout_formal_random_top_tb.v")
# sed -i "s|//----- Default net type -----|\`define REGISTER_WIDTH 100|g" $(find . -type f -name "fabric_eight_mult_20x18_unsigned_regout_formal_random_top_tb.v")
sed -i "s|clk_fm\[15\] = 1'b0;|clk_fm\[15\] = clock0;|g" $(find . -type f -name "fabric_eight_mult_20x18_unsigned_regout_top_formal_verification.v")
sed -i "s|global_resetn_fm\[0\] = 1'b0;|global_resetn_fm\[0\] = 1'b1;|g" $(find . -type f -name "fabric_eight_mult_20x18_unsigned_regout_top_formal_verification.v")
# sed -i "s|dumpvars(1|dumpvars(0|g" $(find . -type f -name "fabric_eight_mult_20x18_unsigned_regout_formal_random_top_tb.v")
